# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - release
  - devel
cache: packages

sudo: required

env: 
  - _R_CHECK_CRAN_INCOMING_=FALSE
  - CODECOV_TOKEN="05ad7f6d-d1b0-4da9-8977-f00c2f18699d"

r_packages:
  - covr
  - devtools

r_github_packages:
  - c5sire/kmerize

after_success:
  - Rscript -e 'library(kmerize);'