# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
cache: packages
r: bioc-release
install:
  - R script 'source("https://install-github.me/r-lib/remotes")'